import { TextInputProps, InputProps } from './InputAttribute'

export type InputDataType = {
  firstName: TextInputProps,
  lastName: TextInputProps,
  firstKanaName: TextInputProps,
  lastKanaName: TextInputProps,
  email: TextInputProps,
  tel: TextInputProps,
  postalCode: TextInputProps,
  address1: TextInputProps,
  address2: TextInputProps,
  password: TextInputProps,
  contact: TextInputProps,
  year: TextInputProps,
  month : TextInputProps,
  day: TextInputProps,
  name: TextInputProps,
  payDay: TextInputProps,
  price: TextInputProps,
  discount: InputProps,
  payId: TextInputProps,
  payName: InputProps,
  categoryId: TextInputProps,
  categoryName: InputProps,
  bankId: TextInputProps,
  bankName: InputProps,
  debitDay: TextInputProps,
  startAggregation: TextInputProps,
  endAggregation: TextInputProps,
  fixedPattern: InputProps,
  Jan: TextInputProps,
  Feb: TextInputProps,
  Mar: TextInputProps,
  Apr: TextInputProps,
  May: TextInputProps,
  Jun: TextInputProps,
  Jul: TextInputProps,
  Aug: TextInputProps,
  Sept: TextInputProps,
  Oct: TextInputProps,
  Nov: TextInputProps,
  Dec: TextInputProps,
  startMonth: TextInputProps,
  monthPattern: InputProps,
  incomeDay: TextInputProps,
}
